services:
  adminer:
      image: adminer
      restart: always
      ports:
      - 8080:8080
 
  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    ports:
        - 8081:8081
    env_file:
      - .env      
     