services:
  videodb:
      image: mariadb:10.9.4
      restart: always #always, no, on-failure, unless-stopped
      env_file:
      - .env
      ports:
        - 3306:3306
     
      volumes:
        - rdb:/var/lib/mysql

  adminer:
      image: adminer
      restart: always
      ports:
      - 8080:8080
  
  video_api:
    image: araani/video-api:v1.0
    restart: always
    build:
        context: video_api
        dockerfile: Dockerfile
    ports:
        - 8000:8000
    env_file:
        - .env
    # This should be set seperately, not in the .env file, because we are also using the .env file in local development and in
    # our database container. By adding this seperate environment variable, we define that the ENVIRONMENT we are working with
    # is in DOCKER. This will use other settings than the local development settings.
    environment:
        ENVIRONMENT: DOCKER

  dashboard:
    image: araani/aab:v1.0
    restart: always
    build:
      context: dashboard
      dockerfile: Dockerfile
    ports:
      - 8050:8050
    expose:
      - 8050
    volumes:
    - type: bind
      source: D:/VideoLibrary
      target: /var/lib/VideoLibrary
    - type: bind
      source: D:/aabData
      target: /var/lib/aabData
    env_file:
      - .env
    environment:
      ENVIRONMENT: DOCKER

volumes:
  rdb:
      
     